server {
    listen 80;
    listen [::]:80;
    server_name wepaper.plainlist.space;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        try_files $uri =404;
    }

    location / {
        return 301 https://wepaper.plainlist.space$request_uri;
    }
}
